language: generic
install: true
script:
- mkdir build
- cp *.html build
deploy:
  provider: s3
  access_key_id: AKIAI2ZPRPGECF27TPNA
  secret_access_key:
    secure: LHl0rHADWVhdnQPKxHQ0XhgauLWkCCdL+YlrK4ClL4Mssp3bOkj7AWpvQgqJezpJ8DxJjz0cwoJLTXWwBEpcTQ4Zqz83Kn5bzF8s1wgonmBPxL/a+EQ5ySyopvUNrm853EKOE/VcozKZuzCx5LEITl6pTswbuw4qgXiBkHlvW0JXgBQ9EuhatSSbTNqcQ6bBymBWKcCdzk1lejCYMmPDCnJhjzwcUazmVjxIJZHcbdHYaZkK2Ftvjk5p04TRPo1Ub8a9SOhtjK13Tc5mQr1wi9ClsXpbFT4u9lW+c6qFjPUCuN40uE4Tyj2tzZuLnpqvTAAxP25OKyM1JSSlxRH0PTXuwCeyAkMq7kz51Zz9Wf7LQSiNZBJtH21CB/3gDQhrXWxhIj9NirtjeNhg5LZ97ArA/i3IS1Etzikt+uVdH7xrFi8gZ4lNnpP3EWAicTGLbhK1QmC+kLWjew2WSnbKApmTpJnMLk3/d+MezoSrW8UW7C1M6sx4Lx705rFhSRO1Z8L+2KtwGK+sFgRYBuoFeWxP9vkskz1F1e2kIB9VpUMX5g4QbfiVy/UpQWe5MT1yhDo/57FOXrP7JAHn2rsf/TsL5dosK9hGfKa2PQnof03Vv0V7TuJfX56C1aowfQz0Eazss38UIJsir2Vn77yguTWBY9DZZuHu67VNqq/wSr0=
  bucket: xinkuo.me
  local-dir: build
  on:
    repo: xkuokuo/xkuokuo.homepage
