language: generic
install: true
script:
- mkdir build
- cp *.html build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: xinkuo.me
  local-dir: build
  on:
    repo: xkuokuo/xkuokuo.homepage
  skip_cleanup: true
