language: node_js
node_js:
  - "8.9.1"
install:
- npm install
script:
- npm run build
- rm -rf build/private
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "xinkuo.me"
  local-dir: build
  on:
    repo: xkuokuo/xkuokuo.homepage
  skip_cleanup: true
