AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Api:
    Cors:
      AllowHeaders: '''*'''
      AllowMethods: '''*'''
      AllowOrigin: '''*'''
Parameters:
  APIDomainName:
    Default: api.xinkuo.me
    Description: domain name for API endpoint
    Type: String
  RecipientEmail:
    Default: dummy@dummy.abc
    Description: Address of recipient of contact form submitted details
    Type: String
Resources:
  APIGatewayUsagePlan:
    Properties:
      ApiStages:
      - ApiId:
          Ref: ServerlessRestApi
        Stage:
          Ref: ServerlessRestApiProdStage
      Description: Trial Plan 50 requests per day
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 1
        RateLimit: 1
      UsagePlanName: OneTPSPlan
    Type: AWS::ApiGateway::UsagePlan
  ContactEmailSNS:
    Properties:
      DisplayName:
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - Contact
      Subscription:
      - Endpoint:
          Ref: RecipientEmail
        Protocol: email
      TopicName: ContactMeSNS
    Type: AWS::SNS::Topic
  ContactMeAPICustomDomain:
    DependsOn: ContactMeFunction
    Properties:
      DomainName:
        Ref: APIDomainName
      EndpointConfiguration:
        Types:
        - REGIONAL
      RegionalCertificateArn: arn:aws:acm:us-east-1:198711792892:certificate/02539496-55d0-4d48-bb04-638acb4e13ed
    Type: AWS::ApiGateway::DomainName
  ContactMeAPIPathMapping:
    DependsOn: ContactMeAPICustomDomain
    Properties:
      DomainName:
        Ref: APIDomainName
      RestApiId:
        Ref: ServerlessRestApi
      Stage:
        Ref: ServerlessRestApiProdStage
    Type: AWS::ApiGateway::BasePathMapping
  ContactMeFunction:
    DependsOn: ContactEmailSNS
    Properties:
      CodeUri: s3://hello-world-kuoxin/4d0bd2d696300a7d9f27b07d1f1fa7f6
      Environment:
        Variables:
          TOPIC_ARN:
            Ref: ContactEmailSNS
      Events:
        ContactMePostAPI:
          Properties:
            Method: post
            Path: /contact-me
          Type: Api
      Handler: contact_me_lambda.handler
      Role:
        Fn::GetAtt:
        - SNSPublishRole
        - Arn
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  SNSPublishRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - sns:Publish
            Effect: Allow
            Resource:
              Ref: ContactEmailSNS
          - Action:
            - logs:*
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: ContactMeMessagePublishPolicy
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
